config/routes.rb
Rails.application.routes.draw do
  resources :duties
  root 'duties#index'
  

end

app/models/duty.rb
class Duty < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :load_nav_duties

  def load_nav_duties
    @nav_duties = Duty.all.group_by(&:category)
  end
end

app/controllers/duties_controller.rb
class DutiesController < ApplicationController
  before_action :set_duty, only: [:show, :edit, :update, :destroy]

  # GET /duties
  # GET /duties.json
  def index
    @duties = Duty.where(category: params[:category])
  end

  # GET /duties/1
  # GET /duties/1.json
  def show
  end

  # GET /duties/new
  def new
    @duty = Duty.new
  end

  # GET /duties/1/edit
  def edit
  end

  # POST /duties
  # POST /duties.json
  def create
    @duty = Duty.new(duty_params)

    respond_to do |format|
      if @duty.save
        format.html { redirect_to @duty, notice: 'Duty was successfully created.' }
        format.json { render :show, status: :created, location: @duty }
      else
        format.html { render :new }
        format.json { render json: @duty.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /duties/1
  # PATCH/PUT /duties/1.json
  def update
    respond_to do |format|
      if @duty.update(duty_params)
        format.html { redirect_to @duty, notice: 'Duty was successfully updated.' }
        format.json { render :show, status: :ok, location: @duty }
      else
        format.html { render :edit }
        format.json { render json: @duty.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /duties/1
  # DELETE /duties/1.json
  def destroy
    @duty.destroy
    respond_to do |format|
      format.html { redirect_to duties_url, notice: 'Duty was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_duty
      @duty = Duty.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def duty_params
      params.require(:duty).permit(:name, :party_size, :min_level, :min_item_level, :time_limit, :category, :sync_level)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/duties_helper.rb
module DutiesHelper
end

app/views/duties/_form.html.erb
<%= form_for(@duty) do |f| %>
  <% if @duty.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@duty.errors.count, "error") %> prohibited this duty from being saved:</h2>

      <ul>
      <% @duty.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="small-10">
      <div class="row">
        <div class="small-2 columns"><%= f.label :name %></div>
        <div class="small-10 columns"><%= f.text_field :name %></div>
      </div>
    </div>
    <div class="small-10">
      <div class="row">
        <div class="small-2 columns"><%= f.label :players %></div>
        <div class="small-10 columns"><%= f.number_field :players %></div>
      </div>
    </div>
    <div class="small-10">
      <div class="row">
        <div class="small-2 columns"><%= f.label :level %></div>
        <div class="small-10 columns"><%= f.number_field :level %></div>
      </div>
    </div>
    <div class="small-10">
      <div class="row">
        <div class="small-2 columns"><%= f.label :time_limit %></div>
        <div class="small-10 columns"><%= f.number_field :time_limit %></div>
      </div>
    </div>
    <div class="small-10">
      <div class="row">
        <div class="small-2 columns"><%= f.label :category %></div>
        <div class="small-10 columns"><%= f.text_field :category %></div>
      </div>
    </div>
    <div class="small-10">
      <div class="row">
        <div class="small-2 columns"><%= f.label :sync_level %></div>
        <div class="small-10 columns"><%= f.number_field :sync_level %></div>
      </div>
    </div>
    <div class="small-10">
      <div class="row">
        <div class="small-10 small-offset-2 columns"><%= f.submit class: 'button' %></div>
      </div>
    </div>
  </div>
<% end %>

app/views/duties/edit.html.erb
<div class="row">
  <div class="small-10">
    <h1>Editing Duty</h1>
  </div>
</div>

<%= render 'form' %>

<%= link_to 'Show', @duty %> |
<%= link_to 'Back', duties_path %>

app/views/duties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Duties</h1>

<%# TODO: this should be converted to divs and stacked for mobile %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Size</th>
      <th>Level</th>
      <th>iLvl</th>
      <th>Time</th>
      <th>Sync</th>
    </tr>
  </thead>

  <tbody>
    <% @duties.each do |duty| %>
      <tr>
        <td><%= link_to duty.name, duty %></td>
        <td><%= duty.party_size %></td>
        <td><%= duty.min_level %></td>
        <td><%= duty.min_item_level %></td>
        <td><%= duty.time_limit %></td>
        <td><%= duty.sync_level %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Duty', new_duty_path, class: 'button success radius small' %>

app/views/duties/new.html.erb
<h1>New Duty</h1>

<%= render 'form' %>

<%= link_to 'Back', duties_path %>

app/views/duties/show.html.haml
%p#notice= notice

%table
  %tbody
    %tr
      %th Name
      %td= @duty.name
    %tr
      %th Party Size
      %td= @duty.party_size
    %tr
      %th Minimum Level
      %td= @duty.min_level
    %tr
      %th Minimum Item Level
      %td= @duty.min_item_level
    %tr
      %th Time Limit
      %td= @duty.time_limit
    %tr
      %th Category
      %td= @duty.category
    %tr
      %th Sync Level
      %td= @duty.sync_level

-# <%#= link_to 'Edit', edit_duty_path(@duty) %> |
-# <%#= link_to 'Back', duties_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'shared/navigation' %>

    <div class="row">
      <div class="large-3 column show-for-large-up">
        <%= render 'shared/duty_nav' %>
      </div>

      <div class="large-9 column">
        <%= yield %>
      </div>
    </div>

    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/shared/_duty_nav.html.erb
<dl class="accordion" data-accordion>
  <% @nav_duties.keys.each do |category| %>
    <dd class="accordion-navigation">
      <a href="#duty_nav_<%= category %>"><%= category.capitalize.humanize %></a>
      <div id="duty_nav_<%= category %>" class="content">
        <ul>
          <% @nav_duties[category].each do |duty| %>
            <li><%= link_to "[#{duty.min_level}] #{duty.name}", duty %></li>
          <% end %>
        </ul>
      </div>
    </dd>
  <% end %>
</dl>

app/views/shared/_navigation.html.erb
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><a href="/">DutyFinder.Info</a></h1>
    </li>

    <li class="toggle-topbar">
      <a href="#"><span>Menu</span></a>
    </li>
  </ul>

  <section class="top-bar-section">
    <ul class="right">
      <li class="hide-for-medium"><%= link_to 'Dungeons', duties_path(category: 'Dungeons') %></li>
      <li class="hide-for-medium"><%= link_to 'Raids', duties_path(category: 'Raids') %></li>
      <li class="hide-for-medium"><%= link_to 'Guildhests', duties_path(category: 'Guildhests') %></li>
      <li class="hide-for-medium"><%= link_to 'Trials', duties_path(category: 'Trials') %></li>
      <li class="hide-for-medium"><%= link_to 'PvP', duties_path(category: 'PvP') %></li>
      <li class="has-dropdown show-for-medium">
        <a href="#">Duty Types</a>
        <ul class="dropdown">
          <li><%= link_to 'Dungeons', duties_path(category: 'Dungeons') %></li>
          <li><%= link_to 'Raids', duties_path(category: 'Raids') %></li>
          <li><%= link_to 'Guildhests', duties_path(category: 'Guildhests') %></li>
          <li><%= link_to 'Trials', duties_path(category: 'Trials') %></li>
          <li><%= link_to 'PvP', duties_path(category: 'PvP') %></li>
        </ul>
      </li>
      <li class="has-form">
        <div class="row collapse">
          <div class="small-8 columns">
            <input type="text" placeholder="Stuff" name="some_name" value="">
          </div>
          <div class="small-4 columns">
            <a href="#" class="alert button expand">Search</a>
          </div>
        </div>
      </li>
    </ul>
  </section>
</nav>